# Generated by Django 3.1.1 on 2020-09-15 11:26

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=500)),
                ('Address', models.CharField(max_length=500)),
                ('City', models.CharField(max_length=500)),
                ('State', models.CharField(max_length=500)),
                ('Zip', models.CharField(max_length=500)),
                ('NameOnCard', models.CharField(max_length=500)),
                ('CCNumber', models.IntegerField()),
                ('ExpMonth', models.CharField(max_length=20)),
                ('ExpYear', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=400)),
                ('slug', models.CharField(max_length=500, unique=True)),
                ('About', models.CharField(default='Its Good', max_length=1000)),
                ('Video', models.TextField(default='Not Available', max_length=500)),
                ('Image', models.ImageField(upload_to='media')),
                ('Cast', models.TextField(default='...', max_length=1000)),
                ('Rank', models.IntegerField(default='1')),
                ('MoviesGenre', multiselectfield.db.fields.MultiSelectField(choices=[('ACT', 'ACTION'), ('ADV', 'ADVENTURE'), ('COM', 'COMEDY'), ('CR', 'CRIME'), ('SCI-FY', 'SCI-FY'), ('ANI', 'ANIMATION'), ('HOR', 'HORROR'), ('SH', 'SUPERHERO'), ('DR', 'DRAMA')], max_length=35)),
                ('Field', models.CharField(choices=[('In Theatre 2020', 'In Theatre 2020'), ('Coming Soon', 'Coming Soon'), ('IMDB RATING', 'IMDB RATING')], max_length=200)),
                ('Imdb_rating', models.CharField(blank=True, default='Not Yet Rated', max_length=200)),
                ('Price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=1)),
                ('checkout', models.BooleanField(default=False)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.movie')),
            ],
        ),
        migrations.CreateModel(
            name='Tv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=500)),
                ('slug', models.CharField(default=1, max_length=500, unique=True)),
                ('Image', models.ImageField(upload_to='media')),
                ('About', models.CharField(default='Its Good', max_length=1000)),
                ('Cast', models.TextField(default='...', max_length=1000)),
                ('Rank', models.IntegerField()),
                ('SeriesGenre', multiselectfield.db.fields.MultiSelectField(choices=[('ACT', 'ACTION'), ('ADV', 'ADVENTURE'), ('COM', 'COMEDY'), ('CR', 'CRIME'), ('SCI-FY', 'SCI-FY'), ('ANI', 'ANIMATION'), ('HOR', 'HORROR'), ('SH', 'SUPERHERO'), ('DR', 'DRAMA')], max_length=35)),
                ('Field', models.CharField(choices=[('POPULAR', 'POPULAR'), ('Coming Soon', 'Coming Soon'), ('RATING', 'IMDB RATING')], default=1, max_length=200)),
                ('Imdb_rating', models.CharField(blank=True, default='Not Yet Rated', max_length=200)),
                ('Price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TotalCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout', models.BooleanField(default=False)),
                ('movieitems', models.ManyToManyField(to='home.OrderMovie')),
            ],
        ),
    ]
