# Generated by Django 3.1.1 on 2020-09-15 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_totalcart_cartname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='ExpMonth',
            new_name='ExpDate',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='ExpYear',
        ),
    ]
