# Generated by Django 3.1.1 on 2020-09-15 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_majoritems_trailers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='majoritems',
            name='Imdb_rating',
        ),
    ]
